# Generated by Django 5.1.1 on 2025-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_bloodflowlog_date_alter_medicationlog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexualintercourselog',
            name='date',
            field=models.DateField(),
        ),
    ]
