# Generated by Django 5.1.1 on 2025-03-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_sexualintercourselog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodflowlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='date',
            field=models.DateField(),
        ),
    ]
